---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
- shell: hostname
  register: current_hostname

- name: mysql | Install MySQL Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server-5.7
    - mysql-client-5.7
    - python-mysqldb
    - mytop


- name: Configure MySQL Password Lifetime
  lineinfile: dest=/etc/mysql/my.cnf
    regexp="default_password_lifetime\s*=.*"
    line="default_password_lifetime = 0"
    state=present
    backrefs=yes

- name: Ensure MySQL is started to change root password
  service: name=mysql state=started

- name: Set MySQL root user password
  mysql_user: name=root password={{ mysql.root_password }} host="{{ item }}" priv=*.*:ALL,GRANT state=present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf for cur user
  become: false
  template: src=my.cnf.j2 dest="~/.my.cnf"

- name: copy .my.cnf for root
  become: true
  template: src=my.cnf.j2 dest="/root/.my.cnf"
